#! /bin/sh

##==> Initial Setup
#################################
# Start sxhkd if it's not already running
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
# Set window manager name to LG3D to fix some Java applications display issues
wmname LG3D

##==> Workspaces Configuration
#################################
# Define workspaces on the primary monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9
# Uncomment to define workspaces on YOUR_MONITOR (for multiple monitors setup)
#bspc monitor YOUR_MONITOR -d 6 7 8 9

# Enable window focus follow mouse pointer
bspc config focus_follows_pointer true

##==> Window Appearance
#################################
# Set the border colors for focused and normal windows
bspc config focused_border_color "#b4befe"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# Set mouse cursor to left pointer
xsetroot -cursor_name left_ptr

##==> Gaps and Window Management
#################################
# Configure gaps and window gap size
bspc config gapless_monocle false
bspc config window_gap 10

# Configure actions for moving and resizing floating windows with the mouse (mod4 = Super/Windows key)
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

##==> Rules
#################################
bspc rule -a feh state=floating
bspc rule -a '*:sun-awt-X11-XWindowPeer' manage=off

##==> Resources and Utilities
#################################
xrdb merge ~/.Xresources # Load Xresources
picom --config $HOME/.config/bspwm/picom.conf &  # Start the compositor for window effects
sh ~/.config/bspwm/polybar/scripts/launch.sh  # Start polybar
dunst -config $HOME/.config/bspwm/dunstrc &  # Start notification daemon
pgrep -x redshift > /dev/null || redshift &  # Start redshift
feh --no-fehbg --bg-fill ~/Wallpapers/current/background.png  # Set wallpapers

##==> Autostart Applications
#################################
flameshot & # Screenshot tool
greenclip daemon & # Clipboard manager
